// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type ActiveMetricRestriction struct {
	MetricName string `json:"metricName"`
	RestrictedMetricTypes json.RawMessage `json:"restrictedMetricTypes"`
}

type BatchRunPivotReportsRequest struct {
	Requests json.RawMessage `json:"requests"`
}

type BatchRunPivotReportsResponse struct {
	Kind string `json:"kind"`
	PivotReports json.RawMessage `json:"pivotReports"`
}

type BatchRunReportsRequest struct {
	Requests json.RawMessage `json:"requests"`
}

type BatchRunReportsResponse struct {
	Kind string `json:"kind"`
	Reports json.RawMessage `json:"reports"`
}

type BetweenFilter struct {
	FromValue json.RawMessage `json:"fromValue"`
	ToValue json.RawMessage `json:"toValue"`
}

type CaseExpression struct {
	DimensionName string `json:"dimensionName"`
}

type CheckCompatibilityRequest struct {
	CompatibilityFilter string `json:"compatibilityFilter"`
	DimensionFilter json.RawMessage `json:"dimensionFilter"`
	Dimensions json.RawMessage `json:"dimensions"`
	MetricFilter json.RawMessage `json:"metricFilter"`
	Metrics json.RawMessage `json:"metrics"`
}

type CheckCompatibilityResponse struct {
	DimensionCompatibilities json.RawMessage `json:"dimensionCompatibilities"`
	MetricCompatibilities json.RawMessage `json:"metricCompatibilities"`
}

type Cohort struct {
	DateRange json.RawMessage `json:"dateRange"`
	Dimension string `json:"dimension"`
	Name string `json:"name"`
}

type CohortReportSettings struct {
	Accumulate bool `json:"accumulate"`
}

type CohortSpec struct {
	CohortReportSettings json.RawMessage `json:"cohortReportSettings"`
	Cohorts json.RawMessage `json:"cohorts"`
	CohortsRange json.RawMessage `json:"cohortsRange"`
}

type CohortsRange struct {
	EndOffset int `json:"endOffset"`
	Granularity string `json:"granularity"`
	StartOffset int `json:"startOffset"`
}

type ConcatenateExpression struct {
	Delimiter string `json:"delimiter"`
	DimensionNames json.RawMessage `json:"dimensionNames"`
}

type DateRange struct {
	EndDate string `json:"endDate"`
	Name string `json:"name"`
	StartDate string `json:"startDate"`
}

type Dimension struct {
	DimensionExpression json.RawMessage `json:"dimensionExpression"`
	Name string `json:"name"`
}

type DimensionCompatibility struct {
	Compatibility string `json:"compatibility"`
	DimensionMetadata json.RawMessage `json:"dimensionMetadata"`
}

type DimensionExpression struct {
	Concatenate json.RawMessage `json:"concatenate"`
	LowerCase json.RawMessage `json:"lowerCase"`
	UpperCase json.RawMessage `json:"upperCase"`
}

type DimensionHeader struct {
	Name string `json:"name"`
}

type DimensionMetadata struct {
	ApiName string `json:"apiName"`
	Category string `json:"category"`
	CustomDefinition bool `json:"customDefinition"`
	DeprecatedApiNames json.RawMessage `json:"deprecatedApiNames"`
	Description string `json:"description"`
	UiName string `json:"uiName"`
}

type DimensionOrderBy struct {
	DimensionName string `json:"dimensionName"`
	OrderType string `json:"orderType"`
}

type DimensionValue struct {
	Value string `json:"value"`
}

type Filter struct {
	BetweenFilter json.RawMessage `json:"betweenFilter"`
	FieldName string `json:"fieldName"`
	InListFilter json.RawMessage `json:"inListFilter"`
	NumericFilter json.RawMessage `json:"numericFilter"`
	StringFilter json.RawMessage `json:"stringFilter"`
}

type FilterExpression struct {
	AndGroup json.RawMessage `json:"andGroup"`
	Filter json.RawMessage `json:"filter"`
	NotExpression json.RawMessage `json:"notExpression"`
	OrGroup json.RawMessage `json:"orGroup"`
}

type FilterExpressionList struct {
	Expressions json.RawMessage `json:"expressions"`
}

type InListFilter struct {
	CaseSensitive bool `json:"caseSensitive"`
	Values json.RawMessage `json:"values"`
}

type Metadata struct {
	Dimensions json.RawMessage `json:"dimensions"`
	Metrics json.RawMessage `json:"metrics"`
	Name string `json:"name"`
}

type Metric struct {
	Expression string `json:"expression"`
	Invisible bool `json:"invisible"`
	Name string `json:"name"`
}

type MetricCompatibility struct {
	Compatibility string `json:"compatibility"`
	MetricMetadata json.RawMessage `json:"metricMetadata"`
}

type MetricHeader struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type MetricMetadata struct {
	ApiName string `json:"apiName"`
	BlockedReasons json.RawMessage `json:"blockedReasons"`
	Category string `json:"category"`
	CustomDefinition bool `json:"customDefinition"`
	DeprecatedApiNames json.RawMessage `json:"deprecatedApiNames"`
	Description string `json:"description"`
	Expression string `json:"expression"`
	Type string `json:"type"`
	UiName string `json:"uiName"`
}

type MetricOrderBy struct {
	MetricName string `json:"metricName"`
}

type MetricValue struct {
	Value string `json:"value"`
}

type MinuteRange struct {
	EndMinutesAgo int `json:"endMinutesAgo"`
	Name string `json:"name"`
	StartMinutesAgo int `json:"startMinutesAgo"`
}

type NumericFilter struct {
	Operation string `json:"operation"`
	Value json.RawMessage `json:"value"`
}

type NumericValue struct {
	DoubleValue float64 `json:"doubleValue"`
	Int64Value string `json:"int64Value"`
}

type OrderBy struct {
	Desc bool `json:"desc"`
	Dimension json.RawMessage `json:"dimension"`
	Metric json.RawMessage `json:"metric"`
	Pivot json.RawMessage `json:"pivot"`
}

type Pivot struct {
	FieldNames json.RawMessage `json:"fieldNames"`
	Limit string `json:"limit"`
	MetricAggregations json.RawMessage `json:"metricAggregations"`
	Offset string `json:"offset"`
	OrderBys json.RawMessage `json:"orderBys"`
}

type PivotDimensionHeader struct {
	DimensionValues json.RawMessage `json:"dimensionValues"`
}

type PivotHeader struct {
	PivotDimensionHeaders json.RawMessage `json:"pivotDimensionHeaders"`
	RowCount int `json:"rowCount"`
}

type PivotOrderBy struct {
	MetricName string `json:"metricName"`
	PivotSelections json.RawMessage `json:"pivotSelections"`
}

type PivotSelection struct {
	DimensionName string `json:"dimensionName"`
	DimensionValue string `json:"dimensionValue"`
}

type PropertyQuota struct {
	ConcurrentRequests json.RawMessage `json:"concurrentRequests"`
	PotentiallyThresholdedRequestsPerHour json.RawMessage `json:"potentiallyThresholdedRequestsPerHour"`
	ServerErrorsPerProjectPerHour json.RawMessage `json:"serverErrorsPerProjectPerHour"`
	TokensPerDay json.RawMessage `json:"tokensPerDay"`
	TokensPerHour json.RawMessage `json:"tokensPerHour"`
	TokensPerProjectPerHour json.RawMessage `json:"tokensPerProjectPerHour"`
}

type QuotaStatus struct {
	Consumed int `json:"consumed"`
	Remaining int `json:"remaining"`
}

type ResponseMetaData struct {
	CurrencyCode string `json:"currencyCode"`
	DataLossFromOtherRow bool `json:"dataLossFromOtherRow"`
	EmptyReason string `json:"emptyReason"`
	SchemaRestrictionResponse json.RawMessage `json:"schemaRestrictionResponse"`
	SubjectToThresholding bool `json:"subjectToThresholding"`
	TimeZone string `json:"timeZone"`
}

type Row struct {
	DimensionValues json.RawMessage `json:"dimensionValues"`
	MetricValues json.RawMessage `json:"metricValues"`
}

type RunPivotReportRequest struct {
	CohortSpec json.RawMessage `json:"cohortSpec"`
	CurrencyCode string `json:"currencyCode"`
	DateRanges json.RawMessage `json:"dateRanges"`
	DimensionFilter json.RawMessage `json:"dimensionFilter"`
	Dimensions json.RawMessage `json:"dimensions"`
	KeepEmptyRows bool `json:"keepEmptyRows"`
	MetricFilter json.RawMessage `json:"metricFilter"`
	Metrics json.RawMessage `json:"metrics"`
	Pivots json.RawMessage `json:"pivots"`
	Property string `json:"property"`
	ReturnPropertyQuota bool `json:"returnPropertyQuota"`
}

type RunPivotReportResponse struct {
	Aggregates json.RawMessage `json:"aggregates"`
	DimensionHeaders json.RawMessage `json:"dimensionHeaders"`
	Kind string `json:"kind"`
	Metadata json.RawMessage `json:"metadata"`
	MetricHeaders json.RawMessage `json:"metricHeaders"`
	PivotHeaders json.RawMessage `json:"pivotHeaders"`
	PropertyQuota json.RawMessage `json:"propertyQuota"`
	Rows json.RawMessage `json:"rows"`
}

type RunRealtimeReportRequest struct {
	DimensionFilter json.RawMessage `json:"dimensionFilter"`
	Dimensions json.RawMessage `json:"dimensions"`
	Limit string `json:"limit"`
	MetricAggregations json.RawMessage `json:"metricAggregations"`
	MetricFilter json.RawMessage `json:"metricFilter"`
	Metrics json.RawMessage `json:"metrics"`
	MinuteRanges json.RawMessage `json:"minuteRanges"`
	OrderBys json.RawMessage `json:"orderBys"`
	ReturnPropertyQuota bool `json:"returnPropertyQuota"`
}

type RunRealtimeReportResponse struct {
	DimensionHeaders json.RawMessage `json:"dimensionHeaders"`
	Kind string `json:"kind"`
	Maximums json.RawMessage `json:"maximums"`
	MetricHeaders json.RawMessage `json:"metricHeaders"`
	Minimums json.RawMessage `json:"minimums"`
	PropertyQuota json.RawMessage `json:"propertyQuota"`
	RowCount int `json:"rowCount"`
	Rows json.RawMessage `json:"rows"`
	Totals json.RawMessage `json:"totals"`
}

type RunReportRequest struct {
	CohortSpec json.RawMessage `json:"cohortSpec"`
	CurrencyCode string `json:"currencyCode"`
	DateRanges json.RawMessage `json:"dateRanges"`
	DimensionFilter json.RawMessage `json:"dimensionFilter"`
	Dimensions json.RawMessage `json:"dimensions"`
	KeepEmptyRows bool `json:"keepEmptyRows"`
	Limit string `json:"limit"`
	MetricAggregations json.RawMessage `json:"metricAggregations"`
	MetricFilter json.RawMessage `json:"metricFilter"`
	Metrics json.RawMessage `json:"metrics"`
	Offset string `json:"offset"`
	OrderBys json.RawMessage `json:"orderBys"`
	Property string `json:"property"`
	ReturnPropertyQuota bool `json:"returnPropertyQuota"`
}

type RunReportResponse struct {
	DimensionHeaders json.RawMessage `json:"dimensionHeaders"`
	Kind string `json:"kind"`
	Maximums json.RawMessage `json:"maximums"`
	Metadata json.RawMessage `json:"metadata"`
	MetricHeaders json.RawMessage `json:"metricHeaders"`
	Minimums json.RawMessage `json:"minimums"`
	PropertyQuota json.RawMessage `json:"propertyQuota"`
	RowCount int `json:"rowCount"`
	Rows json.RawMessage `json:"rows"`
	Totals json.RawMessage `json:"totals"`
}

type SchemaRestrictionResponse struct {
	ActiveMetricRestrictions json.RawMessage `json:"activeMetricRestrictions"`
}

type StringFilter struct {
	CaseSensitive bool `json:"caseSensitive"`
	MatchType string `json:"matchType"`
	Value string `json:"value"`
}
