// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"ga4-pp-cli/internal/cli"
	"ga4-pp-cli/internal/client"
	"ga4-pp-cli/internal/cliutil"
	"ga4-pp-cli/internal/config"
	"ga4-pp-cli/internal/mcp/cobratree"
	"ga4-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// storeOpenReadOnly is a small indirection so handleSQL/handleSearch can
// share a single open path without redeclaring the store import in both
// handlers.
func storeOpenReadOnly(path string) (*store.Store, error) { return store.OpenReadOnly(path) }

// RegisterTools registers all API operations as MCP tools.
//
// Descriptions are intentionally terse: the Steinberger token-efficiency
// dimension caps full marks at <= 80 tokens/tool, and an agent that has
// already called the `context` tool has the long-form taxonomy locally.
// Verbose API-reference prose belongs in the spec, not on every tool
// invocation. Returns hints (`Returns array` / `Returns object`)
// communicate shape without re-describing the API.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("properties_batch-run-pivot-reports",
			mcplib.WithDescription("Batch GA4 pivot reports. Returns array of pivot report results. Requires property."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("GA4 property ID (numeric, no 'properties/' prefix).")),
			mcplib.WithString("requests", mcplib.Description("Array of pivot report requests (max 5).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:batchRunPivotReports", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "requests", WireName: "requests", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_batch-run-reports",
			mcplib.WithDescription("Batch GA4 reports. Returns array of report results. Requires property."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("GA4 property ID.")),
			mcplib.WithString("requests", mcplib.Description("Array of report requests (max 5).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:batchRunReports", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "requests", WireName: "requests", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_check-compatibility",
			mcplib.WithDescription("Test if a set of GA4 dimensions and metrics is compatible. Returns object listing compatible fields."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("GA4 property ID.")),
			mcplib.WithString("compatibilityFilter", mcplib.Description("Filter to one compatibility class.")),
			mcplib.WithString("dimensionFilter", mcplib.Description("Dimension filter expression.")),
			mcplib.WithString("dimensions", mcplib.Description("Dimensions in the report.")),
			mcplib.WithString("metricFilter", mcplib.Description("Metric filter expression.")),
			mcplib.WithString("metrics", mcplib.Description("Metrics in the report.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:checkCompatibility", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "compatibilityFilter", WireName: "compatibilityFilter", Location: "body"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_get-metadata",
			mcplib.WithDescription("Get the dimension and metric metadata for a GA4 property. Returns object with dimensions and metrics arrays."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Resource name properties/{id}/metadata.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1beta/{name}", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "path"}}, []string{"name"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_run-pivot-report",
			mcplib.WithDescription("Run a GA4 pivot report. Returns object with pivot headers and rows."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("GA4 property ID.")),
			mcplib.WithString("cohortSpec", mcplib.Description("Cohort spec for retention reports.")),
			mcplib.WithString("currencyCode", mcplib.Description("ISO4217 currency override.")),
			mcplib.WithString("dateRanges", mcplib.Description("Date ranges to query.")),
			mcplib.WithString("dimensionFilter", mcplib.Description("Dimension filter expression.")),
			mcplib.WithString("dimensions", mcplib.Description("Dimensions to include.")),
			mcplib.WithString("keepEmptyRows", mcplib.Description("Include all-zero rows when true.")),
			mcplib.WithString("metricFilter", mcplib.Description("Metric filter expression.")),
			mcplib.WithString("metrics", mcplib.Description("Metrics to include.")),
			mcplib.WithString("pivots", mcplib.Description("Pivot layout specs.")),
			mcplib.WithString("returnPropertyQuota", mcplib.Description("Include quota in response.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:runPivotReport", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "cohortSpec", WireName: "cohortSpec", Location: "body"}, {PublicName: "currencyCode", WireName: "currencyCode", Location: "body"}, {PublicName: "dateRanges", WireName: "dateRanges", Location: "body"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "keepEmptyRows", WireName: "keepEmptyRows", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}, {PublicName: "pivots", WireName: "pivots", Location: "body"}, {PublicName: "returnPropertyQuota", WireName: "returnPropertyQuota", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_run-realtime-report",
			mcplib.WithDescription("Run a GA4 realtime report (last 30 minutes). Returns object with rows array."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("GA4 property ID.")),
			mcplib.WithString("dimensionFilter", mcplib.Description("Dimension filter expression.")),
			mcplib.WithString("dimensions", mcplib.Description("Dimensions to include.")),
			mcplib.WithString("limit", mcplib.Description("Row limit (default 10000).")),
			mcplib.WithString("metricAggregations", mcplib.Description("Aggregations to apply.")),
			mcplib.WithString("metricFilter", mcplib.Description("Metric filter expression.")),
			mcplib.WithString("metrics", mcplib.Description("Metrics to include.")),
			mcplib.WithString("minuteRanges", mcplib.Description("Minute-range windows.")),
			mcplib.WithString("orderBys", mcplib.Description("Sort spec.")),
			mcplib.WithString("returnPropertyQuota", mcplib.Description("Include realtime quota in response.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:runRealtimeReport", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "limit", WireName: "limit", Location: "body"}, {PublicName: "metricAggregations", WireName: "metricAggregations", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}, {PublicName: "minuteRanges", WireName: "minuteRanges", Location: "body"}, {PublicName: "orderBys", WireName: "orderBys", Location: "body"}, {PublicName: "returnPropertyQuota", WireName: "returnPropertyQuota", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_run-report",
			mcplib.WithDescription("Run a GA4 report. Returns object with dimensionHeaders, metricHeaders, and rows."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("GA4 property ID.")),
			mcplib.WithString("cohortSpec", mcplib.Description("Cohort spec.")),
			mcplib.WithString("currencyCode", mcplib.Description("ISO4217 currency override.")),
			mcplib.WithString("dateRanges", mcplib.Description("Date ranges to query.")),
			mcplib.WithString("dimensionFilter", mcplib.Description("Dimension filter expression.")),
			mcplib.WithString("dimensions", mcplib.Description("Dimensions to include.")),
			mcplib.WithString("keepEmptyRows", mcplib.Description("Include all-zero rows when true.")),
			mcplib.WithString("limit", mcplib.Description("Row limit (default 10000).")),
			mcplib.WithString("metricAggregations", mcplib.Description("Aggregations to apply.")),
			mcplib.WithString("metricFilter", mcplib.Description("Metric filter expression.")),
			mcplib.WithString("metrics", mcplib.Description("Metrics to include.")),
			mcplib.WithString("offset", mcplib.Description("Offset for paging.")),
			mcplib.WithString("orderBys", mcplib.Description("Sort spec.")),
			mcplib.WithString("returnPropertyQuota", mcplib.Description("Include quota in response.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:runReport", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "cohortSpec", WireName: "cohortSpec", Location: "body"}, {PublicName: "currencyCode", WireName: "currencyCode", Location: "body"}, {PublicName: "dateRanges", WireName: "dateRanges", Location: "body"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "keepEmptyRows", WireName: "keepEmptyRows", Location: "body"}, {PublicName: "limit", WireName: "limit", Location: "body"}, {PublicName: "metricAggregations", WireName: "metricAggregations", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}, {PublicName: "offset", WireName: "offset", Location: "body"}, {PublicName: "orderBys", WireName: "orderBys", Location: "body"}, {PublicName: "returnPropertyQuota", WireName: "returnPropertyQuota", Location: "body"}}, []string{"property"}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get GA4 domain context: resource taxonomy, auth, query tips. Returns object. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Typed local-store tools: sql and search expose the SQLite cache without
	// shelling out. Both require sync to have populated the store first.
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run a read-only SQL query against the local GA4 store. Returns array of result rows. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SELECT/WITH/EXPLAIN/PRAGMA statement.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("FTS5 search over synced GA4 dimensions, metrics, and pages. Returns array of hits. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Phrase to search for.")),
			mcplib.WithString("property", mcplib.Description("Filter results to a single property ID.")),
			mcplib.WithString("limit", mcplib.Description("Max hits to return.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)

	// Intent-grouped tools — agent-friendly verbs that compose multiple
	// endpoint calls behind a steady output shape.
	RegisterIntents(s)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export GOOGLE_ANALYTICS_DATA_OAUTH2C=<your-key>" +
					"\n      Run 'ga4-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export GOOGLE_ANALYTICS_DATA_OAUTH2C=<your-key>" +
					"\n      Run 'ga4-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export GOOGLE_ANALYTICS_DATA_OAUTH2C=<your-key>" +
					"\n      Run 'ga4-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "ga4-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "ga4-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

// handleSQL is the typed MCP tool handler for read-only SQL against the
// local store. Mirrors the `sql` CLI command end-to-end: rejects mutating
// statements, opens the store read-only, and returns a {columns, count,
// rows} object.
func handleSQL(_ context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	q, _ := args["query"].(string)
	q = strings.TrimSpace(q)
	if q == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	if err := cli.GuardReadOnlySQL(q); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	path := dbPath()
	if _, err := os.Stat(path); err != nil {
		return mcplib.NewToolResultError("local store missing at " + path + " — run 'ga4-pp-cli sync schema' first"), nil
	}
	s, err := storeOpenReadOnly(path)
	if err != nil {
		return mcplib.NewToolResultError("open store: " + err.Error()), nil
	}
	defer s.Close()
	rows, err := s.DB().Query(q)
	if err != nil {
		return mcplib.NewToolResultError("query: " + err.Error()), nil
	}
	defer rows.Close()
	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError("columns: " + err.Error()), nil
	}
	out := []map[string]any{}
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError("scan: " + err.Error()), nil
		}
		row := map[string]any{}
		for i, c := range cols {
			if b, ok := vals[i].([]byte); ok {
				row[c] = string(b)
			} else {
				row[c] = vals[i]
			}
		}
		out = append(out, row)
	}
	data, _ := json.Marshal(map[string]any{"columns": cols, "count": len(out), "rows": out})
	return mcplib.NewToolResultText(string(data)), nil
}

// handleSearch is the typed MCP tool handler for FTS5 search against the
// synced dimensions, metrics, and pages tables.
func handleSearch(_ context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	q, _ := args["query"].(string)
	q = strings.TrimSpace(q)
	if q == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	property, _ := args["property"].(string)
	limit := 20
	if v, ok := args["limit"].(string); ok {
		if n, err := strconvAtoi(v); err == nil && n > 0 {
			limit = n
		}
	}
	path := dbPath()
	if _, err := os.Stat(path); err != nil {
		return mcplib.NewToolResultError("local store missing at " + path + " — run 'ga4-pp-cli sync schema' first"), nil
	}
	s, err := storeOpenReadOnly(path)
	if err != nil {
		return mcplib.NewToolResultError("open store: " + err.Error()), nil
	}
	defer s.Close()
	hits, err := s.Search(property, q, limit)
	if err != nil {
		return mcplib.NewToolResultError("search: " + err.Error()), nil
	}
	data, _ := json.Marshal(map[string]any{"count": len(hits), "hits": hits})
	return mcplib.NewToolResultText(string(data)), nil
}

func strconvAtoi(s string) (int, error) {
	n := 0
	for _, r := range s {
		if r < '0' || r > '9' {
			return 0, fmt.Errorf("not a number: %s", s)
		}
		n = n*10 + int(r-'0')
	}
	return n, nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "ga4",
		"description": "Every GA4 Data API endpoint, plus saved report profiles, drift detection, schema search, and quality guards no other...",
		"archetype":   "generic",
		"tool_count":  7,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion ga4-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "GOOGLE_ANALYTICS_DATA_OAUTH2C",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "properties",
				"description": "Manage properties",
				"endpoints":   []string{"batch-run-pivot-reports", "batch-run-reports", "check-compatibility", "get-metadata", "run-pivot-report", "run-realtime-report", "run-report"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Saved report profiles", "command": "profiles run", "description": "Save GA4 report templates by name and re-run them with one command.", "rationale": "Local SQLite stores named report shapes (dimensions, metrics, filters, date range). No GA4 MCP supports recall by name.", "via": "mcp-command-mirror"},
			{"name": "Drift / top-movers", "command": "drift pages", "description": "Show top page-level movers between two periods in one command.", "rationale": "Runs current and prior period in one batchRunReports call, joins locally on pagePath, sorts by absolute % delta. No...", "via": "mcp-command-mirror"},
			{"name": "Realtime watch loop", "command": "watch realtime", "description": "Poll runRealtimeReport on an interval and stream deltas as agent-friendly JSON.", "rationale": "Diffing against the previous tick happens in the local store; no MCP streams realtime deltas.", "via": "mcp-command-mirror"},
			{"name": "FTS schema search", "command": "schema search", "description": "Find the right GA4 dimension or metric by phrase, including custom dimensions/metrics for the property.", "rationale": "FTS5-indexed local cache of getMetadata; finds engagementRate, engagedSessions, userEngagementDuration,...", "via": "mcp-command-mirror"},
			{"name": "Sampling / (other) / quota guard", "command": "reports run", "description": "Every report response auto-surfaces sampling, (other)-bucket overflow, and remaining quota tokens as structured...", "rationale": "Inspects samplingMetadatas, dataLossFromOtherRow, and propertyQuota on every response and emits _warnings: [...] in...", "via": "mcp-command-mirror"},
			{"name": "Compatibility batch", "command": "profiles compat", "description": "Run checkCompatibility for every metric in a saved report profile, returning a dimension-vs-metric compatibility matrix.", "rationale": "checkCompatibility exists in the Data API spec but no MCP exposes it. Saved profiles + batch composition turns it...", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Saved report profiles", "insight": "Local SQLite stores named report shapes (dimensions, metrics, filters, date range). No GA4 MCP supports recall by name."},
			{"topic": "Drift / top-movers", "insight": "Runs current and prior period in one batchRunReports call, joins locally on pagePath, sorts by absolute % delta. No MCP composes this."},
			{"topic": "Realtime watch loop", "insight": "Diffing against the previous tick happens in the local store; no MCP streams realtime deltas."},
			{"topic": "FTS schema search", "insight": "FTS5-indexed local cache of getMetadata; finds engagementRate, engagedSessions, userEngagementDuration, customEvent:* in one query without an API call."},
			{"topic": "Sampling / (other) / quota guard", "insight": "Inspects samplingMetadatas, dataLossFromOtherRow, and propertyQuota on every response and emits _warnings: [...] in agent mode."},
			{"topic": "Compatibility batch", "insight": "checkCompatibility exists in the Data API spec but no MCP exposes it. Saved profiles + batch composition turns it into a debugging superpower."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
