// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"ga4-pp-cli/internal/cli"
	"ga4-pp-cli/internal/client"
	"ga4-pp-cli/internal/cliutil"
	"ga4-pp-cli/internal/config"
	"ga4-pp-cli/internal/mcp/cobratree"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("properties_batch-run-pivot-reports",
			mcplib.WithDescription("Returns multiple pivot reports in a batch. All reports must be for the same GA4 Property. Required: property. Optional: requests."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("A Google Analytics GA4 property identifier whose events are tracked. Specified in the URL path and not the body. To...")),
			mcplib.WithString("requests", mcplib.Description("Individual requests. Each request has a separate pivot report response. Each batch request is allowed up to 5 requests.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:batchRunPivotReports", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "requests", WireName: "requests", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_batch-run-reports",
			mcplib.WithDescription("Returns multiple reports in a batch. All reports must be for the same GA4 Property. Required: property. Optional: requests."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("A Google Analytics GA4 property identifier whose events are tracked. Specified in the URL path and not the body. To...")),
			mcplib.WithString("requests", mcplib.Description("Individual requests. Each request has a separate report response. Each batch request is allowed up to 5 requests.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:batchRunReports", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "requests", WireName: "requests", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_check-compatibility",
			mcplib.WithDescription("This compatibility method lists dimensions and metrics that can be added to a report request and maintain compatibility. This method fails if the request's dimensions and metrics are incompatible. In Google Analytics, reports fail if they request incompatible dimensions and/or metrics; in that case, you will need to remove dimensions and/or metrics from the incompatible report until the report is compatible. The Realtime and Core reports have different compatibility rules. This method checks compatibility for Core reports. Required: property. Optional: compatibilityFilter, dimensionFilter, dimensions (plus 2 more). Returns the new CheckCompatibilityResponse."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("A Google Analytics GA4 property identifier whose events are tracked. To learn more, see [where to find your Property...")),
			mcplib.WithString("compatibilityFilter", mcplib.Description("Filters the dimensions and metrics in the response to just this compatibility. Commonly used as...")),
			mcplib.WithString("dimensionFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("dimensions", mcplib.Description("The dimensions in this report. `dimensions` should be the same value as in your `runReport` request.")),
			mcplib.WithString("metricFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("metrics", mcplib.Description("The metrics in this report. `metrics` should be the same value as in your `runReport` request.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:checkCompatibility", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "compatibilityFilter", WireName: "compatibilityFilter", Location: "body"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_get-metadata",
			mcplib.WithDescription("Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. In this method, a Google Analytics GA4 Property Identifier is specified in the request, and the metadata response includes Custom dimensions and metrics as well as Universal metadata. For example if a custom metric with parameter name `levels_unlocked` is registered to a property, the Metadata response will contain `customEvent:levels_unlocked`. Universal metadata are dimensions and metrics applicable to any property such as `country` and `totalUsers`. Required: name."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Required. The resource name of the metadata to retrieve. This name field is specified in the URL path and not URL...")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1beta/{name}", []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "path"}}, []string{"name"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_run-pivot-report",
			mcplib.WithDescription("Returns a customized pivot report of your Google Analytics event data. Pivot reports are more advanced and expressive formats than regular reports. In a pivot report, dimensions are only visible if they are included in a pivot. Multiple pivots can be specified to further dissect your data. Required: property. Optional: cohortSpec, currencyCode, dateRanges (plus 7 more)."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("A Google Analytics GA4 property identifier whose events are tracked. Specified in the URL path and not the body. To...")),
			mcplib.WithString("cohortSpec", mcplib.Description("The specification of cohorts for a cohort report. Cohort reports create a time series of user retention for the...")),
			mcplib.WithString("currencyCode", mcplib.Description("A currency code in ISO4217 format, such as 'AED', 'USD', 'JPY'. If the field is empty, the report uses the...")),
			mcplib.WithString("dateRanges", mcplib.Description("The date range to retrieve event data for the report. If multiple date ranges are specified, event data from each...")),
			mcplib.WithString("dimensionFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("dimensions", mcplib.Description("The dimensions requested. All defined dimensions must be used by one of the following: dimension_expression,...")),
			mcplib.WithString("keepEmptyRows", mcplib.Description("If false or unspecified, each row with all metrics equal to 0 will not be returned. If true, these rows will be...")),
			mcplib.WithString("metricFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("metrics", mcplib.Description("The metrics requested, at least one metric needs to be specified. All defined metrics must be used by one of the...")),
			mcplib.WithString("pivots", mcplib.Description("Describes the visual format of the report's dimensions in columns or rows. The union of the fieldNames (dimension...")),
			mcplib.WithString("returnPropertyQuota", mcplib.Description("Toggles whether to return the current state of this Analytics Property's quota. Quota is returned in...")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:runPivotReport", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "cohortSpec", WireName: "cohortSpec", Location: "body"}, {PublicName: "currencyCode", WireName: "currencyCode", Location: "body"}, {PublicName: "dateRanges", WireName: "dateRanges", Location: "body"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "keepEmptyRows", WireName: "keepEmptyRows", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}, {PublicName: "pivots", WireName: "pivots", Location: "body"}, {PublicName: "returnPropertyQuota", WireName: "returnPropertyQuota", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_run-realtime-report",
			mcplib.WithDescription("Returns a customized report of realtime event data for your property. Events appear in realtime reports seconds after they have been sent to the Google Analytics. Realtime reports show events and usage data for the periods of time ranging from the present moment to 30 minutes ago (up to 60 minutes for Google Analytics 360 properties). For a guide to constructing realtime requests & understanding responses, see [Creating a Realtime Report](https://developers.google.com/analytics/devguides/reporting/data/v1/realtime-basics). Required: property. Optional: dimensionFilter, dimensions, limit (plus 6 more)."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("A Google Analytics GA4 property identifier whose events are tracked. Specified in the URL path and not the body. To...")),
			mcplib.WithString("dimensionFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("dimensions", mcplib.Description("The dimensions requested and displayed.")),
			mcplib.WithString("limit", mcplib.Description("The number of rows to return. If unspecified, 10,000 rows are returned. The API returns a maximum of 250,000 rows...")),
			mcplib.WithString("metricAggregations", mcplib.Description("Aggregation of metrics. Aggregated metric values will be shown in rows where the dimension_values are set to...")),
			mcplib.WithString("metricFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("metrics", mcplib.Description("The metrics requested and displayed.")),
			mcplib.WithString("minuteRanges", mcplib.Description("The minute ranges of event data to read. If unspecified, one minute range for the last 30 minutes will be used. If...")),
			mcplib.WithString("orderBys", mcplib.Description("Specifies how rows are ordered in the response.")),
			mcplib.WithString("returnPropertyQuota", mcplib.Description("Toggles whether to return the current state of this Analytics Property's Realtime quota. Quota is returned in...")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:runRealtimeReport", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "limit", WireName: "limit", Location: "body"}, {PublicName: "metricAggregations", WireName: "metricAggregations", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}, {PublicName: "minuteRanges", WireName: "minuteRanges", Location: "body"}, {PublicName: "orderBys", WireName: "orderBys", Location: "body"}, {PublicName: "returnPropertyQuota", WireName: "returnPropertyQuota", Location: "body"}}, []string{"property"}),
	)
	s.AddTool(
		mcplib.NewTool("properties_run-report",
			mcplib.WithDescription("Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name. For a guide to constructing requests & understanding responses, see [Creating a Report](https://developers.google.com/analytics/devguides/reporting/data/v1/basics). Required: property. Optional: cohortSpec, currencyCode, dateRanges (plus 10 more)."),
			mcplib.WithString("property", mcplib.Required(), mcplib.Description("A Google Analytics GA4 property identifier whose events are tracked. Specified in the URL path and not the body. To...")),
			mcplib.WithString("cohortSpec", mcplib.Description("The specification of cohorts for a cohort report. Cohort reports create a time series of user retention for the...")),
			mcplib.WithString("currencyCode", mcplib.Description("A currency code in ISO4217 format, such as 'AED', 'USD', 'JPY'. If the field is empty, the report uses the...")),
			mcplib.WithString("dateRanges", mcplib.Description("Date ranges of data to read. If multiple date ranges are requested, each response row will contain a zero based date...")),
			mcplib.WithString("dimensionFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("dimensions", mcplib.Description("The dimensions requested and displayed.")),
			mcplib.WithString("keepEmptyRows", mcplib.Description("If false or unspecified, each row with all metrics equal to 0 will not be returned. If true, these rows will be...")),
			mcplib.WithString("limit", mcplib.Description("The number of rows to return. If unspecified, 10,000 rows are returned. The API returns a maximum of 250,000 rows...")),
			mcplib.WithString("metricAggregations", mcplib.Description("Aggregation of metrics. Aggregated metric values will be shown in rows where the dimension_values are set to...")),
			mcplib.WithString("metricFilter", mcplib.Description("To express dimension or metric filters.")),
			mcplib.WithString("metrics", mcplib.Description("The metrics requested and displayed.")),
			mcplib.WithString("offset", mcplib.Description("The row count of the start row. The first row is counted as row 0. When paging, the first request does not specify...")),
			mcplib.WithString("orderBys", mcplib.Description("Specifies how rows are ordered in the response.")),
			mcplib.WithString("returnPropertyQuota", mcplib.Description("Toggles whether to return the current state of this Analytics Property's quota. Quota is returned in...")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v1beta/{property}:runReport", []mcpParamBinding{{PublicName: "property", WireName: "property", Location: "path"}, {PublicName: "cohortSpec", WireName: "cohortSpec", Location: "body"}, {PublicName: "currencyCode", WireName: "currencyCode", Location: "body"}, {PublicName: "dateRanges", WireName: "dateRanges", Location: "body"}, {PublicName: "dimensionFilter", WireName: "dimensionFilter", Location: "body"}, {PublicName: "dimensions", WireName: "dimensions", Location: "body"}, {PublicName: "keepEmptyRows", WireName: "keepEmptyRows", Location: "body"}, {PublicName: "limit", WireName: "limit", Location: "body"}, {PublicName: "metricAggregations", WireName: "metricAggregations", Location: "body"}, {PublicName: "metricFilter", WireName: "metricFilter", Location: "body"}, {PublicName: "metrics", WireName: "metrics", Location: "body"}, {PublicName: "offset", WireName: "offset", Location: "body"}, {PublicName: "orderBys", WireName: "orderBys", Location: "body"}, {PublicName: "returnPropertyQuota", WireName: "returnPropertyQuota", Location: "body"}}, []string{"property"}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export GOOGLE_ANALYTICS_DATA_OAUTH2C=<your-key>" +
					"\n      Run 'ga4-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export GOOGLE_ANALYTICS_DATA_OAUTH2C=<your-key>" +
					"\n      Run 'ga4-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export GOOGLE_ANALYTICS_DATA_OAUTH2C=<your-key>" +
					"\n      Run 'ga4-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "ga4-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "ga4-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "ga4",
		"description": "Every GA4 Data API endpoint, plus saved report profiles, drift detection, schema search, and quality guards no other...",
		"archetype":   "generic",
		"tool_count":  7,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion ga4-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "GOOGLE_ANALYTICS_DATA_OAUTH2C",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "properties",
				"description": "Manage properties",
				"endpoints":   []string{"batch-run-pivot-reports", "batch-run-reports", "check-compatibility", "get-metadata", "run-pivot-report", "run-realtime-report", "run-report"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Saved report profiles", "command": "profiles run", "description": "Save GA4 report templates by name and re-run them with one command.", "rationale": "Local SQLite stores named report shapes (dimensions, metrics, filters, date range). No GA4 MCP supports recall by name.", "via": "mcp-command-mirror"},
			{"name": "Drift / top-movers", "command": "drift pages", "description": "Show top page-level movers between two periods in one command.", "rationale": "Runs current and prior period in one batchRunReports call, joins locally on pagePath, sorts by absolute % delta. No...", "via": "mcp-command-mirror"},
			{"name": "Realtime watch loop", "command": "watch realtime", "description": "Poll runRealtimeReport on an interval and stream deltas as agent-friendly JSON.", "rationale": "Diffing against the previous tick happens in the local store; no MCP streams realtime deltas.", "via": "mcp-command-mirror"},
			{"name": "FTS schema search", "command": "schema search", "description": "Find the right GA4 dimension or metric by phrase, including custom dimensions/metrics for the property.", "rationale": "FTS5-indexed local cache of getMetadata; finds engagementRate, engagedSessions, userEngagementDuration,...", "via": "mcp-command-mirror"},
			{"name": "Sampling / (other) / quota guard", "command": "reports run", "description": "Every report response auto-surfaces sampling, (other)-bucket overflow, and remaining quota tokens as structured...", "rationale": "Inspects samplingMetadatas, dataLossFromOtherRow, and propertyQuota on every response and emits _warnings: [...] in...", "via": "mcp-command-mirror"},
			{"name": "Compatibility batch", "command": "profiles compat", "description": "Run checkCompatibility for every metric in a saved report profile, returning a dimension-vs-metric compatibility matrix.", "rationale": "checkCompatibility exists in the Data API spec but no MCP exposes it. Saved profiles + batch composition turns it...", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Saved report profiles", "insight": "Local SQLite stores named report shapes (dimensions, metrics, filters, date range). No GA4 MCP supports recall by name."},
			{"topic": "Drift / top-movers", "insight": "Runs current and prior period in one batchRunReports call, joins locally on pagePath, sorts by absolute % delta. No MCP composes this."},
			{"topic": "Realtime watch loop", "insight": "Diffing against the previous tick happens in the local store; no MCP streams realtime deltas."},
			{"topic": "FTS schema search", "insight": "FTS5-indexed local cache of getMetadata; finds engagementRate, engagedSessions, userEngagementDuration, customEvent:* in one query without an API call."},
			{"topic": "Sampling / (other) / quota guard", "insight": "Inspects samplingMetadatas, dataLossFromOtherRow, and propertyQuota on every response and emits _warnings: [...] in agent mode."},
			{"topic": "Compatibility batch", "insight": "checkCompatibility exists in the Data API spec but no MCP exposes it. Saved profiles + batch composition turns it into a debugging superpower."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
