// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"ga4-pp-cli/internal/client"
	"ga4-pp-cli/internal/config"
	"ga4-pp-cli/internal/store"
	"github.com/spf13/cobra"
)

// cacheReport is the cache section of the doctor output. It surfaces
// per-table row counts and per-scope sync_state cursors so an agent can
// see at a glance whether the local store is empty, partially synced,
// or stale — without having to run `ga4-pp-cli sql` itself.
type cacheReport struct {
	Path            string             `json:"path"`
	Exists          bool               `json:"exists"`
	SchemaVersion   int                `json:"schema_version,omitempty"`
	StoreSchemaWant int                `json:"store_schema_want,omitempty"`
	RowCounts       map[string]int     `json:"row_counts,omitempty"`
	Scopes          []cacheScopeReport `json:"scopes,omitempty"`
	Error           string             `json:"error,omitempty"`
}

// cacheScopeReport is one (property, scope) cursor entry rendered in
// human-friendly form: scope name, age of the last run, and how many
// rows it produced.
type cacheScopeReport struct {
	PropertyID string `json:"property_id"`
	Scope      string `json:"scope"`
	LastRunAt  string `json:"last_run_at"`
	AgeSeconds int64  `json:"age_seconds"`
	LastDate   string `json:"last_date,omitempty"`
	RowCount   int    `json:"row_count"`
}

// collectCacheReport reads $PRESS_DATA_DIR/ga4/data.db (read-only) and
// returns a structured snapshot of cache state. Missing store is not an
// error — the report records exists=false and the caller can render a
// hint to run `sync`. Any partial-read failure is captured in the
// Error field so doctor still emits something agent-parseable.
func collectCacheReport() cacheReport {
	path := store.DefaultPath()
	rep := cacheReport{Path: path}

	if _, err := os.Stat(path); err != nil {
		// First-run state: the store hasn't been created yet. Render a
		// hint without an Error tag so the doctor's pass/fail logic
		// doesn't flag this as a hard failure.
		rep.Exists = false
		return rep
	}
	rep.Exists = true

	s, err := store.OpenReadOnly(path)
	if err != nil {
		rep.Error = fmt.Sprintf("open: %s", err)
		return rep
	}
	defer s.Close()

	if v, err := s.SchemaVersion(); err == nil {
		rep.SchemaVersion = v
		rep.StoreSchemaWant = store.StoreSchemaVersion
	}

	rep.RowCounts = map[string]int{}
	for _, table := range []string{"properties", "dimensions", "metrics", "pages_daily"} {
		if n, err := s.TableRowCount(table); err == nil {
			rep.RowCounts[table] = n
		}
	}

	states, err := s.AllSyncStates()
	if err != nil {
		rep.Error = strings.TrimSpace(rep.Error + " " + fmt.Sprintf("sync_state: %s", err))
		return rep
	}
	now := time.Now().UTC()
	for _, st := range states {
		entry := cacheScopeReport{
			PropertyID: st.PropertyID,
			Scope:      st.Scope,
			LastRunAt:  st.LastRunAt,
			LastDate:   st.LastDate,
			RowCount:   st.RowCount,
		}
		if t, perr := time.Parse(time.RFC3339, st.LastRunAt); perr == nil {
			entry.AgeSeconds = int64(now.Sub(t).Seconds())
		}
		rep.Scopes = append(rep.Scopes, entry)
	}
	return rep
}

// looksLikeDoctorInterstitial reports whether the response body matches a known
// bot-detection challenge page (Cloudflare, Akamai, Vercel, AWS WAF, DataDome,
// PerimeterX). Only fires on the doctor probe — used to distinguish "transport
// reached the wall" from "transport failed entirely." Returns the vendor name
// when matched, or empty string when no match.
//
// Markers are anchored to <title> or vendor-specific strings to avoid
// false-positives on benign content. For example, a recipe titled "Just A
// Moment of Pause Cookies" must NOT match the Cloudflare challenge marker;
// only "<title>just a moment" (the actual interstitial title) does.
func looksLikeDoctorInterstitial(body []byte) string {
	if len(body) == 0 {
		return ""
	}
	limit := len(body)
	if limit > 8192 {
		limit = 8192
	}
	prefix := strings.ToLower(string(body[:limit]))
	if !strings.Contains(prefix, "<title") {
		// Every bot interstitial we recognize sets a <title>; bodies without
		// one are body-only API responses, not challenge pages.
		return ""
	}
	switch {
	case strings.Contains(prefix, "<title>just a moment") || // CF JS challenge
		strings.Contains(prefix, "challenges.cloudflare.com") || // CF Turnstile
		(strings.Contains(prefix, "attention required") && strings.Contains(prefix, "cloudflare")):
		return "Cloudflare"
	case strings.Contains(prefix, "akamai") && (strings.Contains(prefix, "request unsuccessful") || strings.Contains(prefix, "access denied")):
		return "Akamai"
	case strings.Contains(prefix, "x-vercel-mitigated") || strings.Contains(prefix, "x-vercel-challenge-token") ||
		(strings.Contains(prefix, "vercel") && strings.Contains(prefix, "challenge")):
		return "Vercel"
	case strings.Contains(prefix, "request blocked") && strings.Contains(prefix, "aws waf"):
		return "AWS WAF"
	case strings.Contains(prefix, "datadome") && (strings.Contains(prefix, "blocked") || strings.Contains(prefix, "captcha") || strings.Contains(prefix, "challenge")):
		return "DataDome"
	case strings.Contains(prefix, "perimeterx") || strings.Contains(prefix, "px-captcha"):
		return "PerimeterX"
	}
	return ""
}

func newDoctorCmd(flags *rootFlags) *cobra.Command {
	var failOn string
	cmd := &cobra.Command{
		Use:   "doctor",
		Short: "Check CLI health",
		Example: `  ga4-pp-cli doctor
  ga4-pp-cli doctor --json
  ga4-pp-cli doctor --fail-on warn`,
		RunE: func(cmd *cobra.Command, args []string) error {
			report := map[string]any{}

			// Check config
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				report["config"] = fmt.Sprintf("error: %s", err)
			} else {
				report["config"] = "ok"
				report["config_path"] = cfg.Path
				report["base_url"] = cfg.BaseURL
			}

			// Check auth
			if cfg != nil {
				header := cfg.AuthHeader()
				if header == "" {
					report["auth"] = "not configured"
					report["auth_hint"] = "export GOOGLE_ANALYTICS_DATA_OAUTH2C=<your-key>"
				} else {
					report["auth"] = "configured"
					report["auth_source"] = cfg.AuthSource
				}
			}

			// Check auth environment variables
			authEnvSet := []string{}
			authEnvRequiredMissing := []string{}
			authEnvInfo := []string{}
			authEnvOptionalNames := []string{}
			// Validation rejects multi-OR-group specs upstream, so the single optional-satisfied state is sufficient at runtime.
			authEnvOptionalSatisfied := false
			if os.Getenv("GOOGLE_ANALYTICS_DATA_OAUTH2C") != "" {
				authEnvSet = append(authEnvSet, "GOOGLE_ANALYTICS_DATA_OAUTH2C")
			} else {
				authEnvRequiredMissing = append(authEnvRequiredMissing, "GOOGLE_ANALYTICS_DATA_OAUTH2C")
			}
			switch {
			case len(authEnvRequiredMissing) > 0:
				report["env_vars"] = "ERROR missing required: " + strings.Join(authEnvRequiredMissing, ", ")
			case len(authEnvOptionalNames) > 1 && !authEnvOptionalSatisfied:
				report["env_vars"] = "INFO set one of: " + strings.Join(authEnvOptionalNames, " or ")
			case len(authEnvInfo) > 0:
				report["env_vars"] = "INFO " + strings.Join(authEnvInfo, "; ")
			default:
				report["env_vars"] = fmt.Sprintf("OK %d/%d available", len(authEnvSet), 1)
			}

			// Check API connectivity and validate credentials.
			//
			// The doctor uses the same client every other command uses --
			// flags.newClient() returns a *client.Client wrapping whatever
			// transport the spec declared (Surf for browser-chrome, stdlib
			// for standard). A separate stdlib http.Client would silently
			// bypass that choice and report false negatives against
			// Cloudflare-fronted, Akamai-fronted, or otherwise bot-detected
			// sites. By going through flags.newClient(), the doctor's
			// reachability verdict matches what real commands experience.
			if cfg != nil && cfg.BaseURL != "" {
				c, clientErr := flags.newClient()
				if clientErr != nil {
					report["api"] = fmt.Sprintf("client init error: %s", clientErr)
				} else {
					// Step 1: Basic reachability via the configured transport.
					reachBody, reachErr := c.Get("/", nil)
					var reachAPIErr *client.APIError
					switch {
					case reachErr == nil:
						// 2xx response — clearly reachable. Still inspect the
						// body for a known interstitial; some bot walls return
						// 200 with a JS challenge page.
						if vendor := looksLikeDoctorInterstitial(reachBody); vendor != "" {
							report["api"] = fmt.Sprintf("blocked by %s interstitial — the configured transport reached the wall. Try a different network, wait for the IP-level rate limit to clear, or check that the browser-chrome transport is bound correctly.", vendor)
						} else {
							report["api"] = "reachable"
						}
					case errors.As(reachErr, &reachAPIErr):
						// Non-2xx from the server. The network reached, the
						// server responded — that's "reachable" for our
						// purposes. Inspect the response body for a known
						// interstitial first; otherwise note the status.
						status := reachAPIErr.StatusCode
						if vendor := looksLikeDoctorInterstitial([]byte(reachAPIErr.Body)); vendor != "" {
							report["api"] = fmt.Sprintf("blocked by %s interstitial (HTTP %d) — the configured transport reached the wall.", vendor, status)
						} else {
							report["api"] = fmt.Sprintf("reachable (HTTP %d at /)", status)
						}
					default:
						// Network-level failure: DNS, connection refused, TLS,
						// transport init, etc. The transport itself didn't
						// connect.
						report["api"] = fmt.Sprintf("unreachable: %s", reachErr)
					}

					// Step 2: Validate credentials with an authenticated probe.
					authHeader := cfg.AuthHeader()
					if authHeader == "" {
						// No auth configured — skip credential validation
					} else if reachErr != nil && !errors.As(reachErr, &reachAPIErr) {
						report["credentials"] = "skipped (API unreachable)"
					} else {
						verifyPath := "/"
						authParams := map[string]string{}
						authHeaders := map[string]string{}
						authHeaders["Authorization"] = authHeader
						authHeaders["User-Agent"] = "ga4-pp-cli"
						_, authErr := c.GetWithHeaders(verifyPath, authParams, authHeaders)
						var authAPIErr *client.APIError
						switch {
						case authErr == nil:
							report["credentials"] = "valid"
						case errors.As(authErr, &authAPIErr):
							switch {
							case authAPIErr.StatusCode == 401 || authAPIErr.StatusCode == 403:
								// The probe hit the bare base URL because no auth.verify_path
								// is configured in the spec. Many APIs return 401/403 from a
								// bare versioned root regardless of token validity (the path
								// isn't routed but the gateway still demands credentials).
								// Don't claim invalid without certainty — set verify_path to
								// a known-good authenticated GET (e.g. /me, /v1/account, /user)
								// for a definitive verdict.
								report["credentials"] = fmt.Sprintf("inconclusive (HTTP %d from base URL — set auth.verify_path in spec for a definitive probe)", authAPIErr.StatusCode)
							default:
								// Non-auth HTTP error (404, 500, etc.) — don't blame credentials
								report["credentials"] = fmt.Sprintf("ok (HTTP %d from %s, but auth was accepted)", authAPIErr.StatusCode, verifyPath)
							}
						default:
							report["credentials"] = fmt.Sprintf("error: %s", authErr)
						}
					}
				}
			} else if cfg != nil && cfg.BaseURL == "" {
				report["api"] = "not configured (set base_url in config file)"
			}

			report["version"] = version

			// Cache section: surface local-store row counts and sync_state
			// cursors so agents can see freshness without invoking `sql`.
			cache := collectCacheReport()
			report["cache"] = cache

			if flags.asJSON {
				if err := printJSONFiltered(cmd.OutOrStdout(), report, flags); err != nil {
					return err
				}
				return doctorExitForFailOn(failOn, report)
			}

			// Human-readable output with color
			w := cmd.OutOrStdout()
			checkKeys := []struct{ key, label string }{
				{"config", "Config"},
				{"auth", "Auth"},
				{"env_vars", "Env Vars"},
				{"api", "API"},
				{"credentials", "Credentials"},
			}
			for _, ck := range checkKeys {
				v, ok := report[ck.key]
				if !ok {
					continue
				}
				s := fmt.Sprintf("%v", v)
				indicator := green("OK")
				switch {
				case strings.HasPrefix(s, "INFO"):
					indicator = yellow("INFO")
				case strings.HasPrefix(s, "ERROR"):
					indicator = red("FAIL")
				case strings.HasPrefix(s, "optional"):
					// Optional-auth CLI with no key set — informational, not a failure.
					indicator = yellow("INFO")
				case strings.HasPrefix(s, "inconclusive"):
					// The credential probe could not produce a definitive verdict
					// (typically because the bare base URL returns 401/403 even for
					// valid tokens). Surface as WARN, not FAIL — the user's actual
					// commands will reveal a real auth failure if one exists.
					indicator = yellow("WARN")
				case strings.Contains(s, "error") || strings.Contains(s, "not configured") || strings.Contains(s, "unreachable") || strings.Contains(s, "invalid") || strings.Contains(s, "missing"):
					indicator = red("FAIL")
				case s == "not required":
					// Public APIs: no auth needed is a healthy state, not a warning.
					indicator = green("OK")
				case strings.Contains(s, "not ") || strings.Contains(s, "skipped") || strings.Contains(s, "inferred"):
					indicator = yellow("WARN")
				}
				fmt.Fprintf(w, "  %s %s: %s\n", indicator, ck.label, s)
			}
			// Print info keys without status indicator
			for _, key := range []string{"config_path", "base_url", "auth_source", "version"} {
				if v, ok := report[key]; ok {
					fmt.Fprintf(w, "  %s: %v\n", key, v)
				}
			}
			// Print auth setup hints (indented under Auth line)
			if hint, ok := report["auth_hint"]; ok {
				fmt.Fprintf(w, "  hint: %v\n", hint)
			}
			renderCacheReport(w, cache)
			return doctorExitForFailOn(failOn, report)
		},
	}
	cmd.Flags().StringVar(&failOn, "fail-on", "", "Exit non-zero when a health level is reached: stale, error. Default is never.")
	return cmd
}

// renderCacheReport writes the cache section of a human-readable doctor
// run. Output is intentionally short — one heading, one line per table,
// and one line per scope cursor. Agents that want richer detail should
// pass --json and consume the structured `cache` envelope directly.
func renderCacheReport(w interface {
	Write([]byte) (int, error)
}, c cacheReport) {
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "  %s Cache: %s\n", green("OK"), c.Path)
	if !c.Exists {
		fmt.Fprintln(w, "    (not initialized — run 'ga4-pp-cli sync schema' to create)")
		return
	}
	if c.Error != "" {
		fmt.Fprintf(w, "    %s %s\n", yellow("WARN"), c.Error)
	}
	if c.StoreSchemaWant != 0 && c.SchemaVersion != c.StoreSchemaWant {
		fmt.Fprintf(w, "    %s schema_version=%d, binary wants %d (run 'ga4-pp-cli sync schema' to migrate)\n",
			yellow("WARN"), c.SchemaVersion, c.StoreSchemaWant)
	}
	for _, tbl := range []string{"properties", "dimensions", "metrics", "pages_daily"} {
		if n, ok := c.RowCounts[tbl]; ok {
			fmt.Fprintf(w, "    %-12s %d rows\n", tbl, n)
		}
	}
	for _, sc := range c.Scopes {
		age := time.Duration(sc.AgeSeconds) * time.Second
		fmt.Fprintf(w, "    scope=%-12s property=%-10s age=%-10s rows=%d\n",
			sc.Scope, sc.PropertyID, age.Truncate(time.Second), sc.RowCount)
	}
}

// doctorExitForFailOn returns a non-nil error when the report's worst
// status meets or exceeds the --fail-on threshold. "error" always trips
// when any section reports an error; "stale" also trips when the cache
// section is stale. The default empty string means never fail on status.
func doctorExitForFailOn(failOn string, report map[string]any) error {
	if failOn == "" {
		return nil
	}
	worstError := false
	worstStale := false
	for _, v := range report {
		s, ok := v.(string)
		if ok {
			if strings.Contains(s, "error") || strings.Contains(s, "unreachable") || strings.Contains(s, "invalid") || strings.Contains(s, "missing") {
				worstError = true
			}
		}
		if m, ok := v.(map[string]any); ok {
			if st, _ := m["status"].(string); st == "error" {
				worstError = true
			} else if st == "stale" {
				worstStale = true
			}
		}
	}
	switch failOn {
	case "error":
		if worstError {
			return fmt.Errorf("doctor: --fail-on=error triggered")
		}
	case "stale":
		if worstError || worstStale {
			return fmt.Errorf("doctor: --fail-on=stale triggered")
		}
	default:
		return fmt.Errorf("doctor: unknown --fail-on value %q (valid: stale, error)", failOn)
	}
	return nil
}
