// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newPropertiesCheckCompatibilityCmd(flags *rootFlags) *cobra.Command {
	var bodyCompatibilityFilter string
	var bodyDimensionFilter string
	var bodyDimensions string
	var bodyMetricFilter string
	var bodyMetrics string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "check-compatibility [property]",
		Short:       "This compatibility method lists dimensions and metrics that can be added to a report request and maintain...",
		Example:     "  ga4-pp-cli properties check-compatibility example-value",
		Annotations: map[string]string{"pp:endpoint": "properties.check-compatibility", "pp:method": "POST", "pp:path": "/v1beta/{property}:checkCompatibility"},
		RunE: func(cmd *cobra.Command, args []string) error {
			property, err := resolveProperty(args, flags)
			if err != nil {
				return err
			}
			if !stdinBody {
			}
			c, cerr := flags.newClient()
			if cerr != nil {
				return cerr
			}

			path := "/v1beta/{property}:checkCompatibility"
			path = replacePathParam(path, "property", property)
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCompatibilityFilter != "" {
					body["compatibilityFilter"] = bodyCompatibilityFilter
				}
				if bodyDimensionFilter != "" {
					var parsedDimensionFilter any
					if err := json.Unmarshal([]byte(bodyDimensionFilter), &parsedDimensionFilter); err != nil {
						return fmt.Errorf("parsing --dimension-filter JSON: %w", err)
					}
					body["dimensionFilter"] = parsedDimensionFilter
				}
				if bodyDimensions != "" {
					var parsedDimensions any
					if err := json.Unmarshal([]byte(bodyDimensions), &parsedDimensions); err != nil {
						return fmt.Errorf("parsing --dimensions JSON: %w", err)
					}
					body["dimensions"] = parsedDimensions
				}
				if bodyMetricFilter != "" {
					var parsedMetricFilter any
					if err := json.Unmarshal([]byte(bodyMetricFilter), &parsedMetricFilter); err != nil {
						return fmt.Errorf("parsing --metric-filter JSON: %w", err)
					}
					body["metricFilter"] = parsedMetricFilter
				}
				if bodyMetrics != "" {
					var parsedMetrics any
					if err := json.Unmarshal([]byte(bodyMetrics), &parsedMetrics); err != nil {
						return fmt.Errorf("parsing --metrics JSON: %w", err)
					}
					body["metrics"] = parsedMetrics
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "properties",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCompatibilityFilter, "compatibility-filter", "", "Filters the dimensions and metrics in the response to just this compatibility. Commonly used as...")
	cmd.Flags().StringVar(&bodyDimensionFilter, "dimension-filter", "", "To express dimension or metric filters. The fields in the same FilterExpression need to be either all dimensions or...")
	cmd.Flags().StringVar(&bodyDimensions, "dimensions", "", "The dimensions in this report. `dimensions` should be the same value as in your `runReport` request.")
	cmd.Flags().StringVar(&bodyMetricFilter, "metric-filter", "", "To express dimension or metric filters. The fields in the same FilterExpression need to be either all dimensions or...")
	cmd.Flags().StringVar(&bodyMetrics, "metrics", "", "The metrics in this report. `metrics` should be the same value as in your `runReport` request.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
