// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPropertiesGetMetadataCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-metadata [property]",
		Aliases: []string{"get", "metadata"},
		Short: "Returns metadata for dimensions and metrics available in reporting methods.",
		Example: "  ga4-pp-cli properties get-metadata 123456789\n  ga4-pp-cli properties metadata --json    # uses GA_PROPERTY_ID",
		Annotations: map[string]string{"pp:endpoint": "properties.get-metadata", "pp:method": "GET", "pp:path": "/v1beta/{name}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			property, err := resolveProperty(args, flags)
			if err != nil {
				return err
			}
			c, cerr := flags.newClient()
			if cerr != nil {
				return cerr
			}

			path := "/v1beta/properties/" + property + "/metadata"
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	return cmd
}
