// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPropertiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "properties",
		Short: "Manage properties",
	}

	cmd.AddCommand(newPropertiesBatchRunPivotReportsCmd(flags))
	cmd.AddCommand(newPropertiesBatchRunReportsCmd(flags))
	cmd.AddCommand(newPropertiesCheckCompatibilityCmd(flags))
	cmd.AddCommand(newPropertiesGetMetadataCmd(flags))
	cmd.AddCommand(newPropertiesRunPivotReportCmd(flags))
	cmd.AddCommand(newPropertiesRunRealtimeReportCmd(flags))
	cmd.AddCommand(newPropertiesRunReportCmd(flags))
	// Admin API: full property metadata (display name, time zone, currency,
	// account). Lives under properties for discoverability even though it
	// talks to the analyticsadmin host.
	cmd.AddCommand(newPropertiesDescribeCmd(flags))
	return cmd
}
