// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newPropertiesRunReportCmd(flags *rootFlags) *cobra.Command {
	var bodyCohortSpec string
	var bodyCurrencyCode string
	var bodyDateRanges string
	var bodyDimensionFilter string
	var bodyDimensions string
	var bodyKeepEmptyRows bool
	var bodyLimit string
	var bodyMetricAggregations string
	var bodyMetricFilter string
	var bodyMetrics string
	var bodyOffset string
	var bodyOrderBys string
	var bodyReturnPropertyQuota bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "run-report [property]",
		Short:       "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data...",
		Example:     "  ga4-pp-cli properties run-report example-value",
		Annotations: map[string]string{"pp:endpoint": "properties.run-report", "pp:method": "POST", "pp:path": "/v1beta/{property}:runReport"},
		RunE: func(cmd *cobra.Command, args []string) error {
			property, err := resolveProperty(args, flags)
			if err != nil {
				return err
			}
			if !stdinBody {
			}
			c, cerr := flags.newClient()
			if cerr != nil {
				return cerr
			}

			path := "/v1beta/{property}:runReport"
			path = replacePathParam(path, "property", property)
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCohortSpec != "" {
					var parsedCohortSpec any
					if err := json.Unmarshal([]byte(bodyCohortSpec), &parsedCohortSpec); err != nil {
						return fmt.Errorf("parsing --cohort-spec JSON: %w", err)
					}
					body["cohortSpec"] = parsedCohortSpec
				}
				if bodyCurrencyCode != "" {
					body["currencyCode"] = bodyCurrencyCode
				}
				if bodyDateRanges != "" {
					var parsedDateRanges any
					if err := json.Unmarshal([]byte(bodyDateRanges), &parsedDateRanges); err != nil {
						return fmt.Errorf("parsing --date-ranges JSON: %w", err)
					}
					body["dateRanges"] = parsedDateRanges
				}
				if bodyDimensionFilter != "" {
					var parsedDimensionFilter any
					if err := json.Unmarshal([]byte(bodyDimensionFilter), &parsedDimensionFilter); err != nil {
						return fmt.Errorf("parsing --dimension-filter JSON: %w", err)
					}
					body["dimensionFilter"] = parsedDimensionFilter
				}
				if bodyDimensions != "" {
					var parsedDimensions any
					if err := json.Unmarshal([]byte(bodyDimensions), &parsedDimensions); err != nil {
						return fmt.Errorf("parsing --dimensions JSON: %w", err)
					}
					body["dimensions"] = parsedDimensions
				}
				if bodyKeepEmptyRows != false {
					body["keepEmptyRows"] = bodyKeepEmptyRows
				}
				if bodyLimit != "" {
					body["limit"] = bodyLimit
				}
				if bodyMetricAggregations != "" {
					var parsedMetricAggregations any
					if err := json.Unmarshal([]byte(bodyMetricAggregations), &parsedMetricAggregations); err != nil {
						return fmt.Errorf("parsing --metric-aggregations JSON: %w", err)
					}
					body["metricAggregations"] = parsedMetricAggregations
				}
				if bodyMetricFilter != "" {
					var parsedMetricFilter any
					if err := json.Unmarshal([]byte(bodyMetricFilter), &parsedMetricFilter); err != nil {
						return fmt.Errorf("parsing --metric-filter JSON: %w", err)
					}
					body["metricFilter"] = parsedMetricFilter
				}
				if bodyMetrics != "" {
					var parsedMetrics any
					if err := json.Unmarshal([]byte(bodyMetrics), &parsedMetrics); err != nil {
						return fmt.Errorf("parsing --metrics JSON: %w", err)
					}
					body["metrics"] = parsedMetrics
				}
				if bodyOffset != "" {
					body["offset"] = bodyOffset
				}
				if bodyOrderBys != "" {
					var parsedOrderBys any
					if err := json.Unmarshal([]byte(bodyOrderBys), &parsedOrderBys); err != nil {
						return fmt.Errorf("parsing --order-bys JSON: %w", err)
					}
					body["orderBys"] = parsedOrderBys
				}
				if bodyReturnPropertyQuota != false {
					body["returnPropertyQuota"] = bodyReturnPropertyQuota
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "properties",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCohortSpec, "cohort-spec", "", "The specification of cohorts for a cohort report. Cohort reports create a time series of user retention for the...")
	cmd.Flags().StringVar(&bodyCurrencyCode, "currency-code", "", "A currency code in ISO4217 format, such as 'AED', 'USD', 'JPY'. If the field is empty, the report uses the...")
	cmd.Flags().StringVar(&bodyDateRanges, "date-ranges", "", "Date ranges of data to read. If multiple date ranges are requested, each response row will contain a zero based date...")
	cmd.Flags().StringVar(&bodyDimensionFilter, "dimension-filter", "", "To express dimension or metric filters. The fields in the same FilterExpression need to be either all dimensions or...")
	cmd.Flags().StringVar(&bodyDimensions, "dimensions", "", "The dimensions requested and displayed.")
	cmd.Flags().BoolVar(&bodyKeepEmptyRows, "keep-empty-rows", false, "If false or unspecified, each row with all metrics equal to 0 will not be returned. If true, these rows will be...")
	cmd.Flags().StringVar(&bodyLimit, "limit", "", "The number of rows to return. If unspecified, 10,000 rows are returned. The API returns a maximum of 250,000 rows...")
	cmd.Flags().StringVar(&bodyMetricAggregations, "metric-aggregations", "", "Aggregation of metrics. Aggregated metric values will be shown in rows where the dimension_values are set to...")
	cmd.Flags().StringVar(&bodyMetricFilter, "metric-filter", "", "To express dimension or metric filters. The fields in the same FilterExpression need to be either all dimensions or...")
	cmd.Flags().StringVar(&bodyMetrics, "metrics", "", "The metrics requested and displayed.")
	cmd.Flags().StringVar(&bodyOffset, "offset", "", "The row count of the start row. The first row is counted as row 0. When paging, the first request does not specify...")
	cmd.Flags().StringVar(&bodyOrderBys, "order-bys", "", "Specifies how rows are ordered in the response.")
	cmd.Flags().BoolVar(&bodyReturnPropertyQuota, "return-property-quota", false, "Toggles whether to return the current state of this Analytics Property's quota. Quota is returned in...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
