// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Two MCP transports are wired so the same binary can serve both local
// (stdio) and hosted (Streamable HTTP) callers per Anthropic's 2026-04
// MCP guidance. Selection is environment-driven so deployment shapes
// (Docker images, Render services, claude_desktop_config.json) don't
// need a custom command line — set PP_MCP_TRANSPORT=http to switch.

package main

import (
	"fmt"
	"os"

	mcptools "ga4-pp-cli/internal/mcp"
	"github.com/mark3labs/mcp-go/server"
)

func main() {
	s := server.NewMCPServer(
		"Google Analytics Data",
		"1.0.0",
		server.WithToolCapabilities(false),
	)

	mcptools.RegisterTools(s)

	transport := os.Getenv("PP_MCP_TRANSPORT")
	switch transport {
	case "http", "streamable-http", "streamable_http":
		addr := os.Getenv("PP_MCP_HTTP_ADDR")
		if addr == "" {
			addr = ":8080"
		}
		httpSrv := server.NewStreamableHTTPServer(s)
		fmt.Fprintf(os.Stderr, "ga4-pp-mcp: serving streamable HTTP on %s\n", addr)
		if err := httpSrv.Start(addr); err != nil {
			fmt.Fprintf(os.Stderr, "MCP HTTP server error: %v\n", err)
			os.Exit(1)
		}
	default:
		if err := server.ServeStdio(s); err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			os.Exit(1)
		}
	}
}
