// Copyright 2026 spindle79. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL        string `toml:"base_url"`
	AuthHeaderVal  string `toml:"auth_header"`
	Headers        map[string]string `toml:"headers,omitempty"`
	AuthSource     string `toml:"-"`
	AccessToken    string `toml:"access_token"`
	RefreshToken   string `toml:"refresh_token"`
	TokenExpiry    time.Time `toml:"token_expiry"`
	ClientID       string `toml:"client_id"`
	ClientSecret   string `toml:"client_secret"`
	Path           string `toml:"-"`
	GoogleAnalyticsDataOauth2c string `toml:"analytics_data_oauth2c"`
	// PropertyID is the default GA4 property numeric ID. Resolved from
	// GA_PROPERTY_ID at load time; commands that take a `<property>` arg
	// fall back to this when the user omits it.
	PropertyID string `toml:"property_id"`
	// CredentialsPath mirrors GOOGLE_APPLICATION_CREDENTIALS at load time
	// purely so doctor/auth-status can report what was resolved without
	// having to re-read the env var.
	CredentialsPath string `toml:"-"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://analyticsdata.googleapis.com",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("GA4_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "ga4-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides
	if v := os.Getenv("GOOGLE_ANALYTICS_DATA_OAUTH2C"); v != "" {
		cfg.GoogleAnalyticsDataOauth2c = v
		cfg.AuthSource = "env:GOOGLE_ANALYTICS_DATA_OAUTH2C"
	}
	if v := os.Getenv("GA_PROPERTY_ID"); v != "" {
		cfg.PropertyID = v
	}
	if v := os.Getenv("GOOGLE_APPLICATION_CREDENTIALS"); v != "" {
		cfg.CredentialsPath = v
		// Google ADC takes precedence over the OAuth user-flow fallback;
		// the actual token mint happens in the client at request time.
		if cfg.AuthSource == "" {
			cfg.AuthSource = "env:GOOGLE_APPLICATION_CREDENTIALS"
		}
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.GoogleAnalyticsDataOauth2c != "" {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("GA4_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.GoogleAnalyticsDataOauth2c != "" {
		c.AuthSource = "env:GOOGLE_ANALYTICS_DATA_OAUTH2C"
		return "Bearer " + c.GoogleAnalyticsDataOauth2c
	}
	if c.AccessToken != "" {
		c.AuthSource = "oauth2"
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

func (c *Config) ClearTokens() error {
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
